name: Funni
version: '${project.version}'
main: com.doontcare.me.Main
api-version: 1.18
authors: [ doontcare ]
description: Funni
commands:
  menu:
    description: Open the main menu
  profile:
    description: View your profile & stats
